language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.6
  - 2.3.2
  - jruby-18mode
  - jruby-19mode
  - jruby-9.0.5.0
  - jruby-9.1.6.0
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
gemfile: .travis.gemfile
before_install:
  - gem install bundler
